## Basic Configuration

baseurl = "https://matheusmrb.com.br"
builddrafts = false
canonifyurls = false
languageCode = "pt-BR"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Matheus Borges"
title = "Matheus Borges"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "discusShortname" # Enable if you want to use Disqus
# googleAnalytics = "UA-XXXXXXXX-X" # Enable if you want to use Google Analytics
enableRobotsTXT = true

## Site Settings
[params]
author = "Matheus Borges"
intro = "SRE Enginner - Testando blog"
description = "Analista de Suporte at [3UP TI](https://ti.3up.tech/)"
authorimage = "pic-profile.png"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
email = "matheusmrb@outlook.com.br"
linkedin = "matheusmrb"
github = "themrbx"
instagram = "matheusmrb"
strava = "67286544"

## Extras
[params.extra]
copyright = "© 2024. Matheus Borges. [Some Rights Reserved](https://creativecommons.org/licenses/by/4.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
name = "posts"
weight = 100
identifier = "posts"
url = "posts/"
[[menu.main]]
name = "about"
identifier = "about"
weight = 200
url = "about/"
[[menu.main]]
name = "projects"
identifier = "projects"
weight = 300
url = "projects/"